// export default 'https://web-chat-labs.herokuapp.com/api/';
export default 'http://localhost:7000/api/';

// =============== Auth ==================//

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

// =============== Users ==================//

export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_FAILURE = 'FETCH_ALL_USERS_FAILURE';

export const FETCH_SINGLE_USER = 'FETCH_SINGLE_USER';
export const FETCH_SINGLE_USER_SUCCESS = 'FETCH_SINGLE_USER_SUCCESS';
export const FETCH_SINGLE_USER_FAILURE = 'FETCH_SINGLE_USER_FAILURE';

export const FETCH_HOTEL_STAFF = 'FETCH_HOTEL_STAFF';
export const FETCH_HOTEL_STAFF_SUCCESS = 'FETCH_HOTEL_STAFF_SUCCESS';
export const FETCH_HOTEL_STAFF_FAILURE = 'FETCH_HOTEL_STAFF_FAILURE';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

// =============== Hotels ==================//

export const CREATE_HOTEL = 'CREATE_HOTEL';
export const CREATE_HOTEL_SUCCESS = 'CREATE_HOTEL_SUCCESS';
export const CREATE_HOTEL_FAILURE = 'CREATE_HOTEL_FAILURE';

export const FETCH_SINGLE_HOTEL = 'FETCH_SINGLE_HOTEL';
export const FETCH_SINGLE_HOTEL_SUCCESS = 'FETCH_SINGLE_HOTEL_SUCCESS';
export const FETCH_SINGLE_HOTEL_FAILURE = 'FETCH_SINGLE_HOTEL_FAILURE';

export const UPDATE_HOTEL = 'UPDATE_HOTEL';
export const UPDATE_HOTEL_SUCCESS = 'UPDATE_HOTEL_SUCCESS';
export const UPDATE_HOTEL_FAILURE = 'UPDATE_HOTEL_FAILURE';

// =============== Rooms ==================//

export const CREATE_ROOM_FOR_HOTEL = 'CREATE_ROOM_FOR_HOTEL';
export const CREATE_ROOM_FOR_HOTEL_SUCCESS = 'CREATE_ROOM_FOR_HOTEL_SUCCESS';
export const CREATE_ROOM_FOR_HOTEL_FAILURE = 'CREATE_ROOM_FOR_HOTEL_FAILURE';

export const FETCH_ROOMS_FOR_HOTEL = 'FETCH_ROOMS_FOR_HOTEL';
export const FETCH_ROOMS_FOR_HOTEL_SUCCESS = 'FETCH_ROOMS_FOR_HOTEL_SUCCESS';
export const FETCH_ROOMS_FOR_HOTEL_FAILURE = 'FETCH_ROOMS_FOR_HOTEL_FAILURE';

export const UPDATE_ROOM_FOR_HOTEL = 'UPDATE_ROOM_FOR_HOTEL';
export const UPDATE_ROOM_FOR_HOTEL_SUCCESS = 'UPDATE_ROOM_FOR_HOTEL_SUCCESS';
export const UPDATE_ROOM_FOR_HOTEL_FAILURE = 'UPDATE_ROOM_FOR_HOTEL_FAILURE';

export const DELETE_ROOM_FOR_HOTEL = 'DELETE_ROOM_FOR_HOTEL';
export const DELETE_ROOM_FOR_HOTEL_SUCCESS = 'DELETE_ROOM_FOR_HOTEL_SUCCESS';
export const DELETE_ROOM_FOR_HOTEL_FAILURE = 'DELETE_ROOM_FOR_HOTEL_FAILURE';

// =============== Chats ==================//

export const CHATS = {
  ADD_MESSAGE: 'ADD_MESSAGE',
  ADD_ACTIVE_CHATS: 'ADD_ACTIVE_CHATS',
  ADD_QUEUED_CHATS: 'ADD_QUEUED_CHATS',
  ADD_QUEUED_CHAT: 'ADD_QUEUED_CHAT',
  REMOVE_QUEUED_CHAT: 'REMOVE_QUEUED_CHAT',
  UPDATE_ACTIVE_CHAT: 'UPDATE_ACTIVE_CHAT',
  SAVE_SOCKET: 'SAVE_SOCKET',
};
